### ISSUE TITLE
Autocomplete shows Playernames when it shouldn't

### ISSUE THREAD

**Issue by Chronophylos** [RLNT/Voucher#2]
**Describe the bug**
Autocomplete shows playernames when it shouldn't.

**Spigot Version**: 1.14.3

**To Reproduce**
1. Type `/voucher create Chronophylos`
2. Then a space and a TAB
3. It will show playernames again

**Expected behavior**
Don't show any options to autocomplete

**Screenshots**
![](https://i.imgur.com/DS69Sev.png)

**Comment by DAmNRelentless** [comment]
Known issue in many plugins since the tab completer automatically suggests player names when nothing is given in the list.
Probably fixable by returning an empty list.

**Comment by Chronophylos** [comment]
fixed in 65d6d173a5ab18f671d193217f6ceaf70c2a4c05
