### ISSUE TITLE
You can create multiple Vouchers at the same time

### ISSUE THREAD

**Issue by Chronophylos** [RLNT/Voucher#3]
**Describe the bug**
You can create multiple Vouchers at the same time

**Spigot Version**: 1.14.3

**To Reproduce**
1. Execute `/voucher create Chronophylos`
2. Repeat Step 1 multiple times
3. Enter a command
4. Enter confirm

**Expected behavior**
The Plugin should stop a user from creating multiple vouchers at the same time.

**Screenshots**
![](https://i.imgur.com/lS5midi.png)

**Comment by DAmNRelentless** [comment]
Could be solved by checking the command inputs if they start with a slash.
Attached voucher commands are entered without a slash to prevent further command execution.

**Comment by Chronophylos** [comment]
fixed in 709a2cc30a8e71413f707d92d1b7cd92bc2326d4
